// <auto-generated />
namespace DatabaseStore.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Maunani : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Maunani));
        
        string IMigrationMetadata.Id
        {
            get { return "201605060639263_Mau-nani"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
